
sudo: required
language: java

jdk:
  - openjdk8

script:
  - mvn -DskipTests=true package

before_deploy:
    - mkdir MiningBuild
    - find . -name '*.jar' -exec cp {} ./MiningBuild \;
    - cd /home/travis/build/galilasmb/jOOQ/MiningBuild
    - tar -zcvf result.tar.gz *
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: result.tar.gz
  name: fetchjar-791f2b353972bf486d454d0732b06ca12eb0430a
  file_glob: true
  overwrite: false
  skip_cleanup: true
  on:
    all_branches: true 
            